### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by p-matvienko**
Developed from scratch

### CODE REVIEW

**Comment by le0pard** [comment]
@p-matvienko thanks. Will check after 29.01.2017 - right now do not have access to working machine and good internet connection.

**Comment by le0pard** [comment]
@p-matvienko Very cool 👍

**Comment by le0pard** [comment]
@p-matvienko Looks like I cannot update package:

```
Upload failed
Your APK needs to have the package name co.catware.PsyRadio.
You need to use a different version code for your APK because you already have one with version code 1.
```

image

**Comment by p-matvienko** [comment]
@le0pard Did you try to change package name and version number?

**Comment by le0pard** [comment]
@p-matvienko trying

**Comment by le0pard** [comment]
@p-matvienko looks like I need your help in this. Can you create another PR?

**Comment by p-matvienko** [comment]
ok. Yes, I can. What should I do next with new pull request?

**Comment by le0pard** [comment]
@p-matvienko Looks like need change package name to "co.catware.PsyRadio" and version

**Comment by p-matvienko** [comment]
Ok, I will do this tomorrow

**Comment by p-matvienko** [comment]
Done.
If you have any other issues, you can provide me an access to Google Play
and I will try to upload an update by myself.

**Comment by le0pard** [comment]
@p-matvienko Yep, I think I can do this. Just need to know your email.

**Comment by le0pard** [comment]
@p-matvienko BTW, app published to store.

**Comment by p-matvienko** [comment]
My email is: matv.pavlo@gmail.com

**Comment by p-matvienko** [comment]
So is updated version already available in the store?

**Comment by le0pard** [comment]
@p-matvienko it should. I just get updated.

**Comment by le0pard** [comment]
@p-matvienko Forgot to say - BIG THANKS! New app looks awesome. 

BTW, ios version also available here https://github.com/le0pard/PsyRadioIOS (if you interesting about update)

**Pull request merged**
